#logging:
#    file:
#        name: app.log
#    level:
#        root: info
server:
  port: 8021
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  cloud:
  #    config:
  #      server:
  #        jdbc:
  #          order: 1
  #          sql: SELECT PROPERTIES.KEY, PROPERTIES.VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
  application:
    name: medsoc-city-services
  #  flyway:
  #    enabled: true
  #    locations: classpath:db/migration
  #    password: Aai@2070
  #    schemas: parkingschema
  #    user: root
#  profiles:
#    active: jdbc
#  security:
#    user:
#      name: root
#      password: Aai@2070

#eureka:
#    client:
#        enabled: true
#        serviceUrl:
#            defaultZone: http://localhost:9000/eureka/